/*
 * @file
 * @brief Module for generating masks from depth images
 */
#pragma once

#include <ros/ros.h>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/opencv.hpp>
#include <ros/console.h>


/*
 * @brief Dynamically generate a mask to filter out background pixels
 * @returns A CV_8UC1 Mat of same size as input image
 */
cv::Mat generate_foreground_mask(const cv::Mat &depth_image, const int &depth_mean_offset_value, const int &mask_dilation_kernel_size);

/*
 * @brief Smooths out the grid generated by software depth registering
 * 
 * May lose some details in image, use with caution
 *
 */
cv::Mat dilate_depth_image(const cv::Mat &depth_image, const int &dilation_kernel_size);
